# -*- coding: utf-8 -*-
"""spotify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UTdmNlRiUkYFPHREWF2TzBOWrHqNLw6f
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set(color_codes=True)

spotify = pd.read_csv('spotify.csv',encoding = "ISO-8859-1")

spotify.head()

spotify.info()

sns.barplot(spotify['Energy'], spotify['Danceability'])

sns.distplot(spotify['Loudness..dB..'])

sns.distplot(spotify['Length.'], kde=False, rug=True);

sns.jointplot(spotify['Acousticness..'], spotify['Speechiness.'])

sns.jointplot(spotify['Acousticness..'], spotify['Speechiness.'], kind="hex")

sns.jointplot(spotify['Acousticness..'], spotify['Speechiness.'], kind="kde")

sns.pairplot(spotify[['Beats.Per.Minute', 'Energy', 'Danceability']])

sns.stripplot(spotify['Track.Name'], spotify['Speechiness.'])

sns.swarmplot(spotify['Energy'], spotify['Danceability'])

sns.boxplot(spotify['Energy'], spotify['Danceability'], hue=spotify['Track.Name'])

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(10,50)

sns.barplot(spotify['Energy'], spotify['Danceability'], hue=spotify['Track.Name'])

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(69,10)

sns.countplot(spotify['Artist.Name'])

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(69,27)

sns.pointplot(spotify['Energy'], spotify['Danceability'], hue=spotify['Artist.Name'])

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(69,27)

sns.lmplot(x="Acousticness..", y="Speechiness.", data=spotify)

sns.lmplot(x="Acousticness..", y="Speechiness.", hue="Track.Name", data=spotify)